code = {
    '200' : 'Request is valid -- Your request is valid',
    '403' : 'Access denied -- You request too many times',
    '404' : 'Request path not found',

    '10001' : 'Error - request failed processed. Please try again',
    '10002' : 'Request not authorized - an API key is required and should be included in all requests',
    '10003' : 'Too many requests - please use WebSocket for live updates. Current limit is %s requests per minute',
    '10004' : 'invalid sign',
    '10005' : 'permission denied for current apikey',
    '10006' : 'System not responding. Request status unknown. Please contact live support',
    '10007' : 'Response timeout from backend server. Delivery and request status unknown',
    '10010' : 'request ip mismatch',
    '10016' : 'Service not available',
    '10017' : 'request path not found or request method is invalid',
    '10018' : 'exceed ip rate limit',
    '20001' : 'Order not exists',
    '20003' : 'missing parameter side',
    '20004' : 'invalid parameter side',
    '20005' : 'missing parameter symbol',
    '20006' : 'invalid parameter symbol',
    '20007' : 'missing parameter order_type',
    '20008' : 'invalid parameter order_type',
    '20009' : 'missing parameter qty',
    '20010' : 'New order rejected.',
    '20011' : 'Cancelation rejected',
    '20012' : 'qty must be greater than zero and less than 1 million',
    '20013' : 'Order does not exist.',
    '20014' : 'Invalid API key format.',
    '20015' : 'Invalid API key or IP.',
    '20016' : 'Trading window not open yet for current pair.',
    '20017' : 'missing parameter order_id',
    '20018' : 'invalid date format',
    '20019' : 'missing parameter stop_px',
    '20020' : 'missing parameter base_price',
    '20021' : 'missing parameter stop_order_id',
    '20022' : 'missing parameter leverage',
    '20023' : 'leverage must be a number',
    '20031' : 'leverage must be greater than zero',
    '20070' : 'missing parameter margin',
    '20071' : 'margin must be greater than zero',
    '20084' : 'order_id or order_link_id is required',
    '30001' : 'order_link_id is repeated',
    '30003' : 'qty must be more than the minimum allowed',
    '30004' : 'qty must be less than the maximum allowed',
    '30005' : 'price exceeds maximum allowed',
    '30007' : 'price exceeds minimum allowed',
    '30008' : 'invalid order_type',
    '30009' : 'no position found',
    '30010' : 'insufficient wallet balance',
    '30011' : 'operation not allowed as position is undergoing liquidation',
    '30012' : 'operation not allowed as position is undergoing ADL',
    '30013' : 'position is in liq or adl status',
    '30014' : 'invalid closing order, qty should not greater than size',
    '30015' : 'invalid closing order, side should be opposite',
    '30016' : 'TS and SL must be cancelled first while closing position',
    '30017' : 'estimated fill price cannot be lower than current Buy liq_price',
    '30018' : 'estimated fill price cannot be higher than current Sell liq_price',
    '30019' : 'cannot attach TP/SL params for non-zero position when placing non-opening position order',
    '30020' : 'position already has TP/SL params',
    '30021' : 'cannot afford estimated position_margin',
    '30022' : 'estimated buy liq_price cannot be higher than current mark_price',
    '30023' : 'estimated sell liq_price cannot be lower than current mark_price',
    '30024' : 'cannot set TP/SL/TS for zero-position',
    '30025' : 'trigger price should bigger than 10% of last price',
    '30026' : 'price too high',
    '30027' : 'price set for Take profit should be higher than Last Traded Price',
    '30028' : 'price set for Stop loss should be between Liquidation price and Last Traded Price',
    '30029' : 'price set for Stop loss should be between Last Traded Price and Liquidation price',
    '30030' : 'price set for Take profit should be lower than Last Traded Price',
    '30031' : 'insufficient available balance for order cost',
    '30032' : 'order has been filled or cancelled',
    '30033' : 'The number of stop orders exceeds maximum limit allowed',
    '30034' : 'no order found',
    '30035' : 'too fast to cancel',
    '30036' : 'the expected position value after order execution exceeds the current risk limit',
    '30037' : 'order already cancelled',
    '30041' : 'no position found',
    '30042' : 'insufficient wallet balance',
    '30043' : 'operation not allowed as position is undergoing liquidation',
    '30044' : 'operation not allowed as position is undergoing AD',
    '30045' : 'operation not allowed as position is not normal status',
    '30049' : 'insufficient available balance',
    '30050' : 'any adjustments made will trigger immediate liquidation',
    '30051' : 'due to risk limit, cannot adjust leverage',
    '30052' : 'leverage can not less than 1',
    '30054' : 'position margin is invalid',
    '30057' : 'requested quantity of contracts exceeds risk limit',
    '30063' : 'reduce-only rule not satisfied',
    '30067' : 'insufficient available balance',
    '30068' : 'exit value must be positive',
    '30074' : 'can''t create the stop order, because you expect the order will be triggered when the LastPrice(or IndexPrice, MarkPrice, determined by trigger_by) is raising to stop_px, but the LastPrice(or IndexPrice, MarkPrice) is already equal to or greater than stop_px, please adjust base_price or stop_px',
    '30075' : 'can''t create the stop order, because you expect the order will be triggered when the LastPrice(or IndexPrice, MarkPrice, determined by trigger_by) is falling to stop_px, but the LastPrice(or IndexPrice, MarkPrice) is already equal to or less than stop_px, please adjust base_price or stop_px',
    '33004' : 'apikey already expired',
    '34026' : 'the limit is no change'
}

def get_error_msg(EC):
    try:
        return code[(str)(EC)]
    except KeyError:
        return False
